builder.CreateFile("xlsx");
var oWorksheet = Api.GetActiveSheet();
oWorksheet.GetRange("A1").SetValue("Text");
oWorksheet.GetRange("A1").WrapText = true;
oWorksheet.GetRange("A2").SetValue("Text");
oWorksheet.GetRange("A2").WrapText = false;
oWorksheet.GetRange("A3").SetValue(oWorksheet.GetRange("A1").GetWrapText());
oWorksheet.GetRange("A4").SetValue(oWorksheet.GetRange("A2").GetWrapText());
builder.SaveFile("xlsx", "GetWrapText.xlsx");
builder.CloseFile();
