sudo: required

language: generic
services:
  - docker
jobs:
  include:
    - stage: Default Dockerfile Test
      script: docker build .
    - stage: Archive Dockerfiles Test
      script: docker build -f Dockerfile-archive .
    - stage: Centos-Based Dockerfiles Test
      script: docker build -f Dockerfile-Centos .
    - stage: Debian develop Dockerfiles Test
      script: docker build -f Dockerfile-Debian-Develop .
    - stage: Running test inside doc-builder-testing
      script:
        - docker build -t doc-builder-testing .
        - docker run doc-builder-testing
