FROM ruby:2.4

MAINTAINER Pavel.Lobashov "shockwavenn@gmail.com"

RUN apt-get update && apt-get -y -q install git curl wget
RUN apt-get update && apt-get -y -q install libmagic-dev

RUN gem install bundler
COPY . /doc-builder-testing
COPY asserts/documentbuilder /usr/bin/documentbuilder
RUN chmod +x /usr/bin/documentbuilder
RUN wget http://repo-doc-onlyoffice-com.s3.amazonaws.com/linux/onlyoffice-documentbuilder/origin/develop/latest/x64/documentbuilder-4.4.1-x64.tar.gz
RUN tar xvf documentbuilder-4.4.1-x64.tar.gz
RUN mv /documentbuilder-4.4.1 /documentbuilder
RUN chmod -R 777 /documentbuilder
WORKDIR /doc-builder-testing
RUN /bin/bash -l -c 'bundle install --without development'
CMD /bin/bash -l -c "documentbuilder; \
                     bundle update; \
                     bundle exec parallel_rspec spec"

