builder.CreateFile("docx");
var oDocument     = Api.GetDocument();
oDocument.CreateNewHistoryPoint();
var oFinalSection, oTable, oParagraph;
oParagraph = Api.CreateParagraph();
oFinalSection   = oDocument.GetFinalSection();
oFinalSection.SetEqualColumns(1, 720);
oTable = Api.CreateTable(3, 3);
oDocument.Push(oTable);
oParagraph.AddColumnBreak();
oDocument.Push(oParagraph);
builder.SaveFile("docx", "add_table_in_two_column.docx");
builder.CloseFile();