builder.CreateFile("xlsx");
var oWorksheet = Api.GetActiveSheet();
oWorksheet.SetColumnWidth(0, 30);
oWorksheet.SetColumnWidth(1, 30);
oWorksheet.GetRange("A2").SetValue("123456");
oWorksheet.GetRange("B2").SetValue("General");
oWorksheet.GetRange("A2").NumberFormat = "General";
oWorksheet.GetRange("A3").SetValue("123456");
oWorksheet.GetRange("B3").SetValue("Number");
oWorksheet.GetRange("A3").NumberFormat = "0.00";
oWorksheet.GetRange("A4").SetValue("123456");
oWorksheet.GetRange("B4").SetValue("Currency");
oWorksheet.GetRange("A4").NumberFormat = "$#,##0.00";
oWorksheet.GetRange("A5").SetValue("123456");
oWorksheet.GetRange("B5").SetValue("Accounting");
oWorksheet.GetRange("A5").NumberFormat = "_($* #,##0.00_)";
oWorksheet.GetRange("A6").SetValue("123456");
oWorksheet.GetRange("B6").SetValue("DateShort");
oWorksheet.GetRange("A6").NumberFormat = "m/d/yyyy";
oWorksheet.GetRange("A7").SetValue("123456");
oWorksheet.GetRange("B7").SetValue("DateLong");
oWorksheet.GetRange("A7").NumberFormat = "[$-F800]dddd, mmmm dd, yyyy";
oWorksheet.GetRange("A8").SetValue("123456");
oWorksheet.GetRange("B8").SetValue("Time");
oWorksheet.GetRange("A8").NumberFormat = "[$-F400]h:mm:ss AM/PM";
oWorksheet.GetRange("A9").SetValue("123456");
oWorksheet.GetRange("B9").SetValue("Percentage");
oWorksheet.GetRange("A9").NumberFormat = "0.00%";
oWorksheet.GetRange("A10").SetValue("123456");
oWorksheet.GetRange("B10").SetValue("Percent");
oWorksheet.GetRange("A10").NumberFormat = "0%";
oWorksheet.GetRange("A11").SetValue("123456");
oWorksheet.GetRange("B11").SetValue("Fraction");
oWorksheet.GetRange("A11").NumberFormat = "# ?/?";
oWorksheet.GetRange("A12").SetValue("123456");
oWorksheet.GetRange("B12").SetValue("Scientific");
oWorksheet.GetRange("A12").NumberFormat = "0.00E+00";
oWorksheet.GetRange("A13").SetValue("123456");
oWorksheet.GetRange("B13").SetValue("Text");
oWorksheet.GetRange("A13").NumberFormat = "@";
builder.SaveFile("xlsx", "SetNumberFormat.xlsx");
builder.CloseFile();
