builder.CreateFile("docx");
var oDocument = Api.GetDocument();
oDocument.CreateNewHistoryPoint();
var oTableStyle = oDocument.GetStyle("Bordered & Lined - Accent 1");
var oTable = Api.CreateTable(3, 3);
oDocument.Push(oTable);
oTable.SetStyle(oTableStyle);
oTable.SetTableLook(false, false, true, true, false, true);
builder.SaveFile("docx", "table_with_styleparametres.docx");
builder.CloseFile();
