builder.CreateFile("docx");
var oDocument = Api.GetDocument();
var oParagraph = oDocument.GetElement(0);
oParagraph.AddText("This is just GetTimeUTC method test");
Api.AddComment(oParagraph, "comment", "John Smith");
var aComments = oDocument.GetAllComments();
aComments[0].SetTimeUTC(Date.now());
var sTimeUTC = aComments[0].GetTimeUTC();
oParagraph = Api.CreateParagraph();
oParagraph.AddText("Creation timestamp in UTC: " + sTimeUTC);
oDocument.Push(oParagraph);
builder.SaveFile("docx", "GetTimeUTC.docx");
builder.CloseFile();
