builder.CreateFile("docx");
var oDocument = Api.GetDocument();
oDocument.CreateNewHistoryPoint();
var oParagraph1, oFinalSection;
oParagraph = Api.CreateParagraph();
oDocument.Push(oParagraph);
oSection = oDocument.CreateSection(oParagraph);
oFinalSection = oDocument.GetFinalSection();
oFinalSection.SetPageSize(12240, 15840);
builder.SaveFile("docx", "page_size_for_section.docx");
builder.CloseFile();
