builder.CreateFile("docx");
let oDocument = Api.GetDocument();
let oNum = oDocument.CreateNumbering('numbered');
let oNumLvl = oNum.GetLevel(0);
let oParagraph = oDocument.GetElement(0);
oParagraph.AddText('Numbered paragraph lvl 1');
oParagraph.SetNumbering(oNumLvl);
let oParagraph1 = Api.CreateParagraph();
oParagraph1.AddText('Page Number ');
let oParagraph2 = Api.CreateParagraph();
oParagraph2.AddText('Paragraph number ');
let oParagraph3 = Api.CreateParagraph();
oParagraph3.AddText('Paragraph number (no context) ');
let oParagraph4 = Api.CreateParagraph();
oParagraph4.AddText('Paragraph number (full context) ');
let oParagraph5 = Api.CreateParagraph();
oParagraph5.AddText('Paragraph text ');
let oParagraph6 = Api.CreateParagraph();
oParagraph6.AddText('Above/below ');
let arrPar = [oParagraph1, oParagraph2, oParagraph3, oParagraph4, oParagraph5, oParagraph6];
arrPar.forEach(element => oDocument.Push(element));
let arrNumParagraphs = oDocument.GetAllNumberedParagraphs();
let oNumParLvl1 = arrNumParagraphs[0];
oParagraph1.AddNumberedCrossRef('pageNum', oNumParLvl1, true, false);
oParagraph2.AddNumberedCrossRef('paraNum', oNumParLvl1, true, false);
oParagraph3.AddNumberedCrossRef('noCtxParaNum', oNumParLvl1, true, false);
oParagraph4.AddNumberedCrossRef('fullCtxParaNum', oNumParLvl1, true, false, ' ');
oParagraph5.AddNumberedCrossRef('text', oNumParLvl1, true);
oParagraph6.AddNumberedCrossRef('aboveBelow', oNumParLvl1, true);
builder.SaveFile("docx", "AddNumberedCrossRef.docx");
builder.CloseFile();
