name: check
on: [push]
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle config set with 'development'
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop check
        run: rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running test inside doc-builder-testing
        run: |
          docker build -t doc-builder-testing .
          docker run doc-builder-testing
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfiles:
          - 'Dockerfile'
          - 'dockerfiles/debian-archive/Dockerfile'
          - 'dockerfiles/centos-7/Dockerfile'
          - 'dockerfiles/debian-develop/Dockerfile'
          - 'dockerfiles/debian-next-release/Dockerfile'
    steps:
      - uses: actions/checkout@v2
      - name: Dockerfile ${{ matrix.dockerfiles }} Test
        run: docker build -f ${{ matrix.dockerfiles }} .
