name: check
on: [push]
jobs:
  run_critical_in_all_dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfiles:
          - "Dockerfiles"
          - "dockerfiles/centos-7/Dockerfile"
          - "dockerfiles/debian-develop/Dockerfile"
          - "dockerfiles/debian-next-release/Dockerfile"
    steps:
      - uses: actions/checkout@v3
      - name: Dockerfile ${{ matrix.dockerfiles }}
        run: |
          docker build -t doc-builder-testing -f ${{ matrix.dockerfiles }} .
          docker run -e "PLATFORM=rspec_critical" doc-builder-testing
