name: check
on: [push]
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Setup system requirements
        run: |
          sudo apt-get -y update
          sudo apt-get -y install imagemagick \
                                  libmagickwand-dev
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle config set with 'development'
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop check
        run: rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'

  run_modified_files_in_default_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history to access other branches
      - name: Fetch master branch
        run: git fetch origin master  # Fetch the master branch
      - name: Running test inside doc-builder-testing
        run: |
          docker build -t doc-builder-testing .
          docker run -t doc-builder-testing in_modified_specs

  run_critical_in_default_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running test inside doc-builder-testing
        run: |
          docker build -t doc-builder-testing .
          docker run -t doc-builder-testing rspec_critical

  run_critical_in_all_dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfiles:
          - "dockerfiles/rockylinux-latest/Dockerfile"
          - "dockerfiles/debian-develop/Dockerfile"
          - "dockerfiles/debian-next-release/Dockerfile"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Dockerfile ${{ matrix.dockerfiles }}
        run: |
          docker build -t doc-builder-testing -f ${{ matrix.dockerfiles }} .
          docker run doc-builder-testing rspec_critical
