name: check
on: [push]
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Setup system requirements
        run: |
          sudo apt-get -y update
          sudo apt-get -y install imagemagick \
                                  libmagickwand-dev
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run RuboCop check
        run: rubocop
      - name: Check that code 100% documented
        run: yardoc . | grep -q '100.00% documented'

  run_all_specs_in_default_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running test inside doc-builder-testing
        run: |
          docker build -t doc-builder-testing .
          docker run -t doc-builder-testing

  run_critical_in_all_dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfiles:
          - "dockerfiles/rockylinux-latest/Dockerfile"
          - "dockerfiles/debian-develop/Dockerfile"
          - "dockerfiles/debian-next-release/Dockerfile"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Dockerfile ${{ matrix.dockerfiles }}
        run: |
          docker build -t doc-builder-testing -f ${{ matrix.dockerfiles }} .
          docker run doc-builder-testing
