name: Run All spec files
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running test inside doc-builder-testing
      run: |
        docker build -t doc-builder-testing .
        docker run doc-builder-testing
