name: units
on: [push, pull_request]
jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running units
        run: |
          docker build -t units -f dockerfiles/units/Dockerfile .
          docker run units
